export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'
export const REVIEW_LIST_RESET = 'REVIEW_LIST_RESET'

export const REVIEW_STARS_REQUEST = 'REVIEW_STARS_REQUEST'
export const REVIEW_STARS_SUCCESS = 'REVIEW_STARS_SUCCESS'
export const REVIEW_STARS_FAIL = 'REVIEW_STARS_FAIL'
export const REVIEW_STARS_RESET = 'REVIEW_STARS_RESET'

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL'
export const REVIEW_DELETE_RESET = 'REVIEW_DELETE_RESET'
