export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'

export const REVIEW_STARS_REQUEST = 'REVIEW_STARS_REQUEST'
export const REVIEW_STARS_SUCCESS = 'REVIEW_STARS_SUCCESS'
export const REVIEW_STARS_FAIL = 'REVIEW_STARS_FAIL'
